[package]
name = "rui-extra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rui = { path = "../rui" }
vger = { git = "https://github.com/audulus/vger-rs" }
euclid = "0.22.6"
