[package]
name = "rui-stuff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rui = { path = "../rui" }
vger = "0.1.7"
euclid = "0.22.6"
